# Generated by Django 4.0.6 on 2022-07-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Editor',
            new_name='Editora',
        ),
    ]
