# Generated by Django 4.0.6 on 2022-07-26 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_itencompra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItenCompra',
            new_name='ItensCompra',
        ),
    ]
